ARG platform="windows/amd64"
FROM --platform=$platform golang:1.15-windowsservercore-1809 AS builder

RUN go get github.com/distribution/distribution/cmd/registry

FROM --platform=$platform mcr.microsoft.com/windows/nanoserver:1809

COPY --from=builder /gopath/bin/registry.exe c:/registry.exe
COPY config.yml /config/config.yml

CMD ["serve", "/config/config.yml"]
ENTRYPOINT ["c:/registry.exe"]
