name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
   
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    paths-ignore:
      - README.md

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

env:
  IMAGE_REPO: micahyoung/registry 
  LINUX_ARM64_IMAGE_ID: micahyoung/registry:linux-amd64
  LINUX_AMD64_IMAGE_ID: micahyoung/registry:linux-arm64
  WINDOWS_AMD64_IMAGE_ID: micahyoung/registry:windows-amd64

jobs:
  push-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build amd64 images
        run: |
          set -o errexit -o pipefail -o nounset

          docker build . --file Dockerfile --build-arg platform=linux/amd64 --tag $IMAGE_REPO

      - name: Log into registry
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push amd64 image
        if: github.event_name == 'push'
        run: |
          docker tag $IMAGE_REPO $LINUX_AMD64_IMAGE_ID
          docker push $LINUX_AMD64_IMAGE_ID

      - name: Recreate manifest list
        if: github.event_name == 'push'
          docker manifest create $IMAGE_REPO:latest $LINUX_AMD64_IMAGE_ID $LINUX_ARM64_IMAGE_ID $WINDOWS_AMD64_IMAGE_ID
          docker manifest push $IMAGE_REPO:latest

  push-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable docker binfmt_misc for ARM image support
        run: |
          set -o errexit -o pipefail -o nounset
          
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build arm64 images
        run: |
          set -o errexit -o pipefail -o nounset

          docker build . --file Dockerfile --build-arg platform=linux/arm64 --tag $IMAGE_REPO

      - name: Log into registry
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push arm64 image
        if: github.event_name == 'push'
        run: |
          docker tag $IMAGE_REPO $LINUX_ARM64_IMAGE_ID
          docker push $LINUX_ARM64_IMAGE_ID

      - name: Recreate manifest list
        if: github.event_name == 'push'
          docker manifest create $IMAGE_REPO:latest $LINUX_AMD64_IMAGE_ID $LINUX_ARM64_IMAGE_ID $WINDOWS_AMD64_IMAGE_ID
          docker manifest push $IMAGE_REPO:latest

  push-windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enable docker cli experimental features (for manifest lists)
        shell: bash
        run: |
          set -o errexit -o pipefail -o nounset

          mkdir ~/.docker
          echo '{"experimental":"enabled"}' > ~/.docker/config.json

      - name: Build amd64 images
        shell: bash
        run: |
          set -o errexit -o pipefail -o nounset

          docker build . --file Dockerfile.windows --build-arg platform=windows/amd64 --tag $IMAGE_REPO

      - name: Log into registry
        if: github.event_name == 'push'
        shell: bash
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push amd64 image
        if: github.event_name == 'push'
        shell: bash
        run: |
          docker tag $IMAGE_REPO $WINDOWS_AMD64_IMAGE_ID
          docker push $WINDOWS_AMD64_IMAGE_ID

      - name: Recreate manifest list
        shell: bash
        if: github.event_name == 'push'
          docker manifest create $IMAGE_REPO:latest $LINUX_AMD64_IMAGE_ID $LINUX_ARM64_IMAGE_ID $WINDOWS_AMD64_IMAGE_ID
          docker manifest push $IMAGE_REPO:latest
